### getAllList
GET http://localhost:3000/lists

### getOneList
GET http://localhost:3000/lists/1

### updateList
PATCH http://localhost:3000/lists/1
Content-Type: application/x-www-form-urlencoded

name=Première liste
&position=1

### create list with PUT
PUT http://localhost:3000/lists/2
Content-Type: application/x-www-form-urlencoded

name=Deuxième liste
&position=2

### delete list
DELETE http://localhost:3000/lists/2